### ISSUE TITLE
Parser for Lambda

### ISSUE THREAD

**Issue by int-index** [MaiaVictor/caramel#4]
I couldn't find a way to turn the expanded lambda form back into Caramel. Reading the source revealed that there's no such way since there's no `parseLambda :: String -> L.Term` function.

**Comment by VictorTaelin** [comment]
There is no such a thing, sorry, although it wouldn't be hard to write one, but, why do you need that, exactly?

**Comment by int-index** [comment]
> why do you need that, exactly?

No particular reason, I just found it strange that the translation is not (entirely) bidirectional.

**Comment by VictorTaelin** [comment]
Oh the bidirectionality is between Caramel and Lambda Calculus, i.e., the languages, not the syntaxes. You could add a parser for the traditional non-sugared lambda calculus, maybe... that didn't even cross my mind, actually. I'll remind that when I update Caramel.

**Comment by int-index** [comment]
> You could add a parser for the traditional non-sugared lambda calculus

Yeah, that's what I had in mind. I'll probably submit a PR if I find the time to implement it, but no promises.
